[project]
name = "nuc-ansible"
version = "0.1.0"
description = "Ansible playbook for setting up the NUC for the droid dataset"
readme = "README.md"
authors = [
    { name = "Yiyun Liu", email = "yiyun@basis.ai" }
]
requires-python = ">=3.13"
dependencies = [
    "ansible>=14.3.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false